### PR TITLE
Change dns to string slice in `ca init` but backwards compatible csv

### LINKED ISSUE #537: `ca init --dns=csv` validated as single DNS name, not a CSV of them
### Subject of the issue
The value passed to the `--dns` flag of `step ca init` is validated incorrectly.

The issue seems to be [here][init.go#L372]. The `ui.DNS()` [validator][validators.go#L46] tests for a single DNS name, not a CSV of them.

### Your environment
* OS - Arch Linux
* Version - Smallstep CLI/0.16.1 (linux/amd64) Release Date: 2021-07-12

### Steps to reproduce
```bash
$ step ca init --dns=[::1] --address=:443 --name=ca --provisioner=jwk --password-file=<(echo foo)
# Works fine
$ step ca init --dns=localhost,127.0.0.1 ...
# Works because 'localhost,127.0.0.1' is a valid host per https://pkg.go.dev/net#SplitHostPort
$ step ca init --dns=localhost,127.0.0.1,[::1] ...
localhost,127.0.0.1,[::1] is not a valid DNS name
```

### Expected behaviour
The third command should continue without error and lead to the expected `ca.json:dnsNames`:
 ```bash
$ step ca init --dns=localhost,127.0.0.1,[::1] --address=:443 --name=ca --provisioner=jwk --password-file=<(echo foo)
$ jq .dnsNames $STEPPATH/config/ca.json
[
    "localhost",
    "127.0.0.1",
    "[::1]"
]
```

### Actual behaviour
The validation error `localhost,127.0.0.1,[::1] is not a valid DNS name` is printed to stderr.

[init.go#L372]: https://github.com/smallstep/cli/blob/master/command/ca/init.go#L372
[validators.go#L46]: https://github.com/smallstep/cli/blob/master/ui/validators.go#L46

### PR DESCRIPTION
**Pull request by dopey**
Fixes #537

### CODE REVIEW

File: command/ca/init.go [hunk 1]
```diff
@@ -366,23 +367,28 @@ func initAction(ctx *cli.Context) (err error) {
...
 			if len(name) == 0 {
 				continue
 			}
+			if err := dnsValidator(name); err != nil {
+				return err
+			}
 			dnsNames = append(dnsNames, strings.TrimSpace(name))
 		}
 
+		fmt.Printf("dnsNames = %+v\n", dnsNames)
```
Comment (maraino) [inline command/ca/init.go:391]: Remove debug statement.

**Review by maraino — CHANGES_REQUESTED** [review]
Looks good to me, but can you remove the debug statement
