### PR TITLE
revoke <serial> must be base 10 or indicate appropriate base

### LINKED ISSUE #698: [Bug]: In `step ca revoke` convert serial number to big int for consistency.
### Steps to Reproduce

`step ca revoke 0x000111` will revoke the string `0x000111` rather than converting to a Big Int for consistency.

### Your Environment

* OS - any
* `step` CLI Version - latest

### Expected Behavior

Convert the input to a consistent value as key to the database.

### Actual Behavior

The value is used directly as a key into the database.

### Additional Context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by dopey**
Fixes #698

### CODE REVIEW

File: command/ca/revoke.go [hunk 1]
```diff
@@ -260,6 +262,13 @@ func revokeCertificateAction(ctx *cli.Context) error {
 		if err := errs.NumberOfArguments(ctx, 1); err != nil {
 			return err
 		}
+
+		_serial := new(big.Int)
+		_serial, ok := _serial.SetString(serial, 0)
+		if !ok {
+			return fmt.Errorf("'%s' is not a valid serial number - use a base 10 representation or add a prefix indicating the base", serial)
+		}
+		serial = _serial.String()
```
Comment (maraino) [inline command/ca/revoke.go:271]:
```suggestion
		sn, ok := new(big.Int).SetString(serial, 0)
		if !ok {
			return fmt.Errorf("'%s' is not a valid serial number - use a base 10 representation or add a prefix indicating the base", serial)
		}
		serial = sn.String()
```

**Review by maraino — APPROVED** [review]
Looks ok, but variables like `_serial` doesn't look very good in Go code. See my suggestion.
