### PR TITLE
Change trimURLPrefix -> trimURL ...

### LINKED ISSUE #245: Step CLI breaks on URLs with trailing slashes
### Subject of the issue

```
% step certificate inspect https://google.com/
failed to connect: dial tcp: lookup google.com/: no such host
```

### Your environment

```
% step version
Smallstep CLI/0.13.3 (darwin/amd64)
Release Date: 2019-10-02 18:36 UTC
```

### Steps to reproduce

```
% step certificate inspect https://google.com/
failed to connect: dial tcp: lookup google.com/: no such host
```

### Expected behaviour

URLs with a trailing slash (or perhaps even "whole URL"?) should be supported as input.

If not that, perhaps the error returned should more accurately reflect the failure mode?

### Actual behaviour

An incorrect error is returned, describing a name lookup failure

### PR DESCRIPTION
**Pull request by dopey**
* Remove trailing '/' if one exists.
* Fixes for inspect, verify, lint, fingerprint

Fixes #245

### CODE REVIEW

File: command/certificate/remote.go [hunk 1]
```diff
@@ -47,18 +47,18 @@ func getPeerCertificates(addr, roots string, insecure bool) ([]*x509.Certificate
...
-func trimURLPrefix(url string) (string, string, bool) {
+// trimURL("https://smallstep.com") -> "https://", "smallstep.com", true
+// trimURL("./certs/root_ca.crt") -> "", "", false
+// trimURL("hTtPs://sMaLlStEp.cOm") -> "hTtPs://", "sMaLlStEp.cOm", true
+func trimURL(url string) (string, string, bool) {
 	tmp := strings.ToLower(url)
 	for _, prefix := range urlPrefixes {
 		if strings.HasPrefix(tmp, prefix) {
-			return url[:len(prefix)], url[len(prefix):], true
+			return url[:len(prefix)], strings.TrimSuffix(url[len(prefix):], "/"), true
```
Comment (maraino) [inline command/certificate/remote.go:61]: I would rather parse that url using `url.Parse(rawurl)` (you will need to rename the argument), and grab the `u.Host`, that would be in the format of `host` or `host:port`.
